import type { AiroConfig } from "./config.js";
import { getApiKeySetupMessage, resolveApiKey } from "./config.js";
import { mapWithConcurrency } from "./concurrency.js";
import {
  removeSectionsForPackages,
  stampPackageSectionVersion,
  type PackageReadme,
} from "./packages.js";
import type { GenerationProgress } from "./progress.js";
import { generateSteeringForPackage } from "./providers/index.js";

/** Max parallel LLM requests (balances speed vs provider rate limits). */
const PARALLEL_REQUESTS = 3;

/** Generate steering markdown for each package via the configured LLM (one request per package). */
export async function generateSteeringContent(
  packages: PackageReadme[],
  config: AiroConfig,
  projectPackages: string[],
  progress?: GenerationProgress,
): Promise<string> {
  if (packages.length === 0) {
    return "";
  }

  const apiKey = resolveApiKey(config);
  if (!apiKey) {
    throw new Error(getApiKeySetupMessage(config));
  }

  progress?.start();

  try {
    const sections = await mapWithConcurrency(
      packages,
      PARALLEL_REQUESTS,
      async (pkg) => {
        progress?.packageStarted();
        const otherPackages = projectPackages.filter((name) => name !== pkg.name);
        try {
          const section = await generateSteeringForPackage(
            pkg,
            config.ai.provider,
            config.ai.model,
            apiKey,
            otherPackages,
          );
          progress?.packageCompleted();
          return stampPackageSectionVersion(section.trim(), pkg.name, pkg.version);
        } catch (error) {
          progress?.packageFailed();
          throw error;
        }
      },
    );

    return sections.join("\n\n");
  } finally {
    progress?.finish();
  }
}

export const STEERING_HEADER = `# airo — package steering
> Auto-generated by airo. Do not edit manually — run \`npx @paavonykanen/airo\` to update.
`;

/** Wrap generated sections with the standard .airo/steering.md header. */
export function assembleSteeringDocument(sections: string): string {
  const body = sections.trim();
  if (!body) {
    return `${STEERING_HEADER}\n`;
  }
  return `${STEERING_HEADER}\n${body}\n`;
}

/**
 * Merge new sections into existing steering output.
 * Strips removed and updated packages before appending replacements.
 */
export async function mergeSteeringSections(
  existingContent: string,
  newSections: string,
  removedPackages: string[],
  updatedPackages: string[] = [],
): Promise<string> {
  const packagesToStrip = [...new Set([...removedPackages, ...updatedPackages])];
  let content = removeSectionsForPackages(existingContent, packagesToStrip);

  const headerMatch = content.match(/^# airo — package steering[\s\S]*?\n\n/);
  const header = headerMatch?.[0] ?? STEERING_HEADER + "\n";
  const body = headerMatch ? content.slice(header.length).trim() : content;

  const mergedBody = [body, newSections.trim()].filter(Boolean).join("\n\n");
  return `${header}${mergedBody}\n`;
}
